### ISSUE TITLE
Feature#1 User-can-search-for-a-recipe 

### ISSUE THREAD

**Issue by lisale841** [lisale841/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> #####   The user will see an input area where they can type in the dish that they would like to make.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create html skeleton to match wireframe.
- [x] Add background image 
- [x] create css layout/class to match the styling of the wireframe
- [x] Add an input area for searching the recipe
- [x] Make the input for the search input required
- [x] Make a submit button
- [x] Ensure it looks nice on both mobile-sized and desktop sized screens
- [x] Listen for the submit event with the submit button.
- [x] Make sure “XmlHttpRequest get” works when submit is pushed.
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
