### ISSUE TITLE
Feature #2 : User-can-see-a-list-of-recipes

### ISSUE THREAD

**Issue by lisale841** [lisale841/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a sibling div to the previous data view 
- [x] create some dummy recipe for the recipe list under that new data view to get feel on how the recipe list should look like
- [x] check to make sure that the recipe list looks good on both mobile and desktop screen
- [x] make sure that when submit was pushed earlier that the previous data view is hidden to show the current recipe list data view
- [x] Create a dom tree in js file to replicate the dummy recipe list format
- [x] delete the dummy recipe from the html file
- [x] loop thru the xmlhttprequest object array and get the image and name properties for each recipe list to plug into dom tree.
- [x] append that recipe onto the page
- [x] make sure it looks good on both mobile and desktop view
- [x] add an addeventlistener for the recipe on click to get xmlhttprequest for details.

- [x]  Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
