### ISSUE TITLE
Feature#3: User-can-see-details-for-a-single-recipe

### ISSUE THREAD

**Issue by lisale841** [lisale841/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a sibling div to the previous data view 
- [x] create a dummy recipe detail under that new data view to get a feel on how the recipe detail should look like
- [x] check to make sure that the recipe looks good on both mobile and desktop screen
- [x] make sure that when you clicked on the recipe on the previous dataview that the previous data view is hidden to show the recipe details page only. 
- [x] delete the dummy recipe from the html file
- [x] loop thru the xmlhttp object array and get the image, name, instructions, and ingredients properties for the recipe to plug into html
- [x] append that recipe details onto the page
- [x] make sure it looks good on both mobile and desktop view
- [x] Test all functionality again in a private browsing session.
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
