### ISSUE TITLE
Feature#4: User-can-save-recipes-in-the-Favorites-list.

### ISSUE THREAD

**Issue by lisale841** [lisale841/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a sibling dataview to the HTML 
- [x] create a dummy recipe favorites under that new data view to get a feel on how the recipe favorites should look like
- [x] Create a dom tree for the favorites
- [x] Delete the dummy recipe favorites
- [x] add a favorites button on the recipe details page
- [x] add navigation item to the navBar for Favorites
- [x] listen for add event listener for the favorite button to update the data model.
- [x] verify that favorites are saved to local storage along with the rest of the data model on page reload.
- [x] if there are no favorites : make sure the favorites show “No favorites available.”
- [x] ensure that when clicking on favorites that the recipe is added to the favorites in the data js
- [x] make sure it looks good on both mobile and desktop view
- [x]  Test all functionality again in a private browsing session.
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
